/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResultadoGeralRouteImport } from './routes/resultado-geral'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as OrdensRouteImport } from './routes/ordens'
import { Route as NovaOrdemRouteImport } from './routes/nova-ordem'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as CustosOperacionaisRouteImport } from './routes/custos-operacionais'
import { Route as CustosFixosRouteImport } from './routes/custos-fixos'
import { Route as ClientesRouteImport } from './routes/clientes'
import { Route as AdminSistemaRouteImport } from './routes/admin-sistema'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const ResultadoGeralRoute = ResultadoGeralRouteImport.update({
  id: '/resultado-geral',
  path: '/resultado-geral',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdensRoute = OrdensRouteImport.update({
  id: '/ordens',
  path: '/ordens',
  getParentRoute: () => rootRouteImport,
} as any)
const NovaOrdemRoute = NovaOrdemRouteImport.update({
  id: '/nova-ordem',
  path: '/nova-ordem',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosOperacionaisRoute = CustosOperacionaisRouteImport.update({
  id: '/custos-operacionais',
  path: '/custos-operacionais',
  getParentRoute: () => rootRouteImport,
} as any)
const CustosFixosRoute = CustosFixosRouteImport.update({
  id: '/custos-fixos',
  path: '/custos-fixos',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesRoute = ClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSistemaRoute = AdminSistemaRouteImport.update({
  id: '/admin-sistema',
  path: '/admin-sistema',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-sistema': typeof AdminSistemaRoute
  '/clientes': typeof ClientesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/custos-operacionais': typeof CustosOperacionaisRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/nova-ordem': typeof NovaOrdemRoute
  '/ordens': typeof OrdensRoute
  '/produtos': typeof ProdutosRoute
  '/resultado-geral': typeof ResultadoGeralRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-sistema': typeof AdminSistemaRoute
  '/clientes': typeof ClientesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/custos-operacionais': typeof CustosOperacionaisRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/nova-ordem': typeof NovaOrdemRoute
  '/ordens': typeof OrdensRoute
  '/produtos': typeof ProdutosRoute
  '/resultado-geral': typeof ResultadoGeralRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/admin-sistema': typeof AdminSistemaRoute
  '/clientes': typeof ClientesRoute
  '/custos-fixos': typeof CustosFixosRoute
  '/custos-operacionais': typeof CustosOperacionaisRoute
  '/equipe': typeof EquipeRoute
  '/financeiro': typeof FinanceiroRoute
  '/login': typeof LoginRoute
  '/nova-ordem': typeof NovaOrdemRoute
  '/ordens': typeof OrdensRoute
  '/produtos': typeof ProdutosRoute
  '/resultado-geral': typeof ResultadoGeralRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin-sistema'
    | '/clientes'
    | '/custos-fixos'
    | '/custos-operacionais'
    | '/equipe'
    | '/financeiro'
    | '/login'
    | '/nova-ordem'
    | '/ordens'
    | '/produtos'
    | '/resultado-geral'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin-sistema'
    | '/clientes'
    | '/custos-fixos'
    | '/custos-operacionais'
    | '/equipe'
    | '/financeiro'
    | '/login'
    | '/nova-ordem'
    | '/ordens'
    | '/produtos'
    | '/resultado-geral'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin-sistema'
    | '/clientes'
    | '/custos-fixos'
    | '/custos-operacionais'
    | '/equipe'
    | '/financeiro'
    | '/login'
    | '/nova-ordem'
    | '/ordens'
    | '/produtos'
    | '/resultado-geral'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AdminSistemaRoute: typeof AdminSistemaRoute
  ClientesRoute: typeof ClientesRoute
  CustosFixosRoute: typeof CustosFixosRoute
  CustosOperacionaisRoute: typeof CustosOperacionaisRoute
  EquipeRoute: typeof EquipeRoute
  FinanceiroRoute: typeof FinanceiroRoute
  LoginRoute: typeof LoginRoute
  NovaOrdemRoute: typeof NovaOrdemRoute
  OrdensRoute: typeof OrdensRoute
  ProdutosRoute: typeof ProdutosRoute
  ResultadoGeralRoute: typeof ResultadoGeralRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resultado-geral': {
      id: '/resultado-geral'
      path: '/resultado-geral'
      fullPath: '/resultado-geral'
      preLoaderRoute: typeof ResultadoGeralRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ordens': {
      id: '/ordens'
      path: '/ordens'
      fullPath: '/ordens'
      preLoaderRoute: typeof OrdensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nova-ordem': {
      id: '/nova-ordem'
      path: '/nova-ordem'
      fullPath: '/nova-ordem'
      preLoaderRoute: typeof NovaOrdemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos-operacionais': {
      id: '/custos-operacionais'
      path: '/custos-operacionais'
      fullPath: '/custos-operacionais'
      preLoaderRoute: typeof CustosOperacionaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/custos-fixos': {
      id: '/custos-fixos'
      path: '/custos-fixos'
      fullPath: '/custos-fixos'
      preLoaderRoute: typeof CustosFixosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes': {
      id: '/clientes'
      path: '/clientes'
      fullPath: '/clientes'
      preLoaderRoute: typeof ClientesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-sistema': {
      id: '/admin-sistema'
      path: '/admin-sistema'
      fullPath: '/admin-sistema'
      preLoaderRoute: typeof AdminSistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AdminSistemaRoute: AdminSistemaRoute,
  ClientesRoute: ClientesRoute,
  CustosFixosRoute: CustosFixosRoute,
  CustosOperacionaisRoute: CustosOperacionaisRoute,
  EquipeRoute: EquipeRoute,
  FinanceiroRoute: FinanceiroRoute,
  LoginRoute: LoginRoute,
  NovaOrdemRoute: NovaOrdemRoute,
  OrdensRoute: OrdensRoute,
  ProdutosRoute: ProdutosRoute,
  ResultadoGeralRoute: ResultadoGeralRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
